### ISSUE TITLE
compatability issue with sleep warp mod

### ISSUE THREAD

**Issue by a-fan9823** [outercloudstudio/Reworked--Sleep-To-Night#1]
Loading both mods at the same time seems to break the game due to both mods modifying the sleeping or bed mechanics causing either a crash or a tick freeze...

**Comment by a-fan9823** [comment]
note this isn't a huge issue just a problem with people who want to sleep the day away and have time run while sleeping

**Comment by outercloudstudio** [comment]
Thank you for reporting this. I'll take a look.

**Comment by a-fan9823** [comment]
Thanks!

**Comment by outercloudstudio** [comment]
It's been a few months 😅 but I finally have time to work on this. Sorry about the wait.

**Comment by outercloudstudio** [comment]
@a-person1908 Support has now been implemented. Go ahead and download the latest version.
