### ISSUE TITLE
Day counter reset

### ISSUE THREAD

**Issue by Fukuyarieru** [outercloudstudio/Reworked--Sleep-To-Night#2]
each time now when you sleep the F3 (world) day counter gets reset back to 0, I assume it is a side effect of something the mod does but still a bug

**Comment by outercloudstudio** [comment]
Thank you. I'll take a look into fixing it this week.

**Comment by outercloudstudio** [comment]
Fixed in 226195479b32b3b2ca78c28dd7f81c252b3bc37e
